import './globals.css';
import { Cairo } from 'next/font/google';

const cairo = Cairo({ subsets: ['latin'], weight:["200", "300", "400", "500", "600", "700", "800", "900", "1000"] });

export const metadata = {
  title: 'Next js Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cairo.className}>{children}</body>
    </html>
  )
}